### ISSUE TITLE
missing images dir

### ISSUE THREAD

**Issue by hyperclock** [txmodxoops/TDMCreate-1.91-alpha-1#3]
when creating a module image there is none.

"Files in ./uploads/tdmcreate/images/repository" is empty

this is on the first page - $DOMAN_NAME/modules/TDMCreate/admin/modules.php?op=new

PS- Shouldn't the "Files" point to "./tdmcreate/assets/images/"

Another point that I almost forgot to mention is that copying the images from "assets" to the given dir does NOT work.

**Comment by txmodxoops** [comment]
Thanks to report this :)

**Comment by txmodxoops** [comment]
Solved in alpha 2
