### ISSUE TITLE
Request: please add "Select all" checkbox

### ISSUE THREAD

**Issue by mambax7** [txmodxoops/TDMCreate-1.91-alpha-1#6]
please add "Select all" checkbox:

![image](https://cloud.githubusercontent.com/assets/613686/7337439/ffbd73aa-ebf7-11e4-966b-357593711bef.png)

**Comment by txmodxoops** [comment]
Done :)
![table_checkbox_checked](https://cloud.githubusercontent.com/assets/539148/7338100/3a7674da-ec41-11e4-946f-3f8080b3d515.gif)
![table_checkbox_unchecked](https://cloud.githubusercontent.com/assets/539148/7338102/43dc3460-ec41-11e4-9d84-1c1ff69e035b.gif)

**Comment by txmodxoops** [comment]
Done
