### ISSUE TITLE
Default values for fields are not being saved

### ISSUE THREAD

**Issue by mambax7** [txmodxoops/TDMCreate-1.91-alpha-1#7]
![image](https://cloud.githubusercontent.com/assets/613686/7337694/1e3539ae-ec01-11e4-8a06-bc486ee8b7b4.png)

**Comment by mambax7** [comment]
Still not fixed in TDMCreate-1.91-alpha-2

**Comment by txmodxoops** [comment]
Pleace Michael!

change in admin/fields.php?op=save the functions !empty() with isset()

**Comment by mambax7** [comment]
Since the field is optional, try to run it by leaving it empty...

**Comment by txmodxoops** [comment]
Do not need those features, I have them deleted both empty and isset

**Comment by txmodxoops** [comment]
If you create new fields, otherwise this works if you use edit, do not save fields.

It is a bug that I can not find

**Comment by txmodxoops** [comment]
Solved in new issues in edit mode
