### ISSUE TITLE
Missing a Handler for a table (in my case: $categoryHandler)

### ISSUE THREAD

**Issue by mambax7** [txmodxoops/TDMCreate-1.91-alpha-1#8]
![image](https://cloud.githubusercontent.com/assets/613686/7337723/f237ae08-ec01-11e4-924a-5c087b7ee4aa.png)

In my case, the line 24 was here:

    22 include_once 'header.php';
    23  // Count elements
    24  $count_category = $categoryHandler->getCount();
    25  $count_news = $newsHandler->getCount();

**Comment by txmodxoops** [comment]
Solved with new variables
